Modules/Appearance/Routes/web.php
<?php


use Illuminate\Support\Facades\Route;

Route::prefix('appearance')->as('appearance.')->middleware('auth')->group(function () {
    Route::get('/', 'AppearanceController@index')->name('index')->middleware('RoutePermissionCheck:appearance.themes.index');

    //themes
    Route::resource('/themes', 'ThemeController')->except('destroy', 'update', 'edit')->middleware('RoutePermissionCheck:appearance.themes.index');
    Route::post('/themes/active', 'ThemeController@active')->name('themes.active')->middleware('RoutePermissionCheck:appearance.themes.index');
    Route::post('/themes/delete', 'ThemeController@destroy')->name('themes.delete')->middleware('RoutePermissionCheck:appearance.themes.index');
});

Modules/Appearance/Entities/Theme.php
<?php

namespace Modules\Appearance\Entities;

use Illuminate\Database\Eloquent\Model;

class Theme extends Model
{

    protected $guarded = ['id'];

}

Modules/Appearance/Http/Controllers/AppearanceController.php
<?php

namespace Modules\Appearance\Http\Controllers;


use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class AppearanceController extends Controller
{

    public function index()
    {
        return view('appearance::index');
    }


    public function create()
    {
        return view('appearance::create');
    }


    public function store(Request $request)
    {
        //
    }





    public function destroy($id)
    {
        //
    }
}

Modules/Appearance/Http/Controllers/ThemeController.php
<?php

namespace Modules\Appearance\Http\Controllers;

use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use \Modules\Appearance\Services\ThemeService;
use Exception;
use ZipArchive;
use Illuminate\Support\Str;
use \Modules\Appearance\Entities\Theme;
use App\Traits\UploadTheme;

class ThemeController extends Controller
{
    use UploadTheme;

    protected $themeService;

    public function __construct(ThemeService $themeService)
    {
        $this->themeService = $themeService;
    }

    public function index()
    {
        try {
            $activeTheme = $this->themeService->activeOne();
            $ThemeList = $this->themeService->getAllActive();
            return view('appearance::theme.index', compact('ThemeList', 'activeTheme'));
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }


    public function create()
    {
        try {
            return view('appearance::theme.components.create');
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    public function active(Request $request)
    {
        if (demoCheck()) {
            return redirect()->back();
        }
        try {
            $this->themeService->isActive($request->only('id'), $request->id);
            $notification = array(
                'messege' => 'Theme Change Successfully.',
                'alert-type' => 'success'
            );
            return redirect(route('appearance.themes.index'))->with($notification);
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    public function store(Request $request)
    {
        if (demoCheck()) {
            return redirect()->back();
        }
        try {
            if ($request->hasFile('themeZip')) {

                $dir = 'theme';
                if (!is_dir($dir))
                    mkdir($dir, 0777, true);

                $path = $request->themeZip->store('theme');

                $request->themeZip->getClientOriginalName();

                $zip = new ZipArchive;
                $res = $zip->open(base_path('public/' . $path));

                $random_dir = Str::random(10);


                $dir = trim($zip->getNameIndex(0), '/');


                if ($res === true) {
                   $zip->extractTo(base_path('public/temp/' . $random_dir . '/theme'));

                    $zip->close();
                } else {
                    dd('could not open');
                }

                $str = file_get_contents(base_path('public/temp/') . $random_dir . '/theme/' . $dir . '/config.json');


                $json = json_decode($str, true);

                if (!empty($json['files'])) {
                    foreach ($json['files'] as $key => $directory) {
                        if ($key == 'asset_path') {
                            if (!is_dir($directory)) {
                                mkdir(base_path($directory), 0777, true);
                            }
                        }
                        if ($key == 'view_path') {
                            if (!is_dir($directory)) {
                                mkdir(base_path($directory), 0777, true);
                            }
                        }
                    }
                }

                // Create/Replace new files.
                if (!empty($json['files'])) {
                    foreach ($json['files'] as $key => $file) {

                        if ($key == 'asset_path') {
                            $src = base_path('public/temp/' . $random_dir . '/theme' . '/' . $json['folder_path'] . '/asset');
                            $dst = base_path($file);

                            $this->recurse_copy($src, $dst);
                        }
                        if ($key == 'view_path') {
                            $src = base_path('public/temp/' . $random_dir . '/theme' . '/' . $json['folder_path'] . '/view');
                            $dst = base_path($file);
                            $this->recurse_copy($src, $dst);
                        }
                    }
                }

                if (Theme::where('name', '!=', $json['name'])) {

                    Theme::create([
                        'name' => $json['name'],
                        'title' => $json['title'],
                        'image' => $json['image'],
                        'version' => $json['version'],
                        'folder_path' => $json['folder_path'],
                        'live_link' => $json['live_link'],
                        'description' => $json['description'],
                        'is_active' => $json['is_active'],
                        'status' => $json['status'],
                        'tags' => $json['tags']
                    ]);
                }
            }
            if (is_dir('theme') || is_dir('temp')) {

                $this->delete_directory(base_path('public/theme'));
                $this->delete_directory(base_path('public/temp'));
            }


            Toastr::success("New Theme Upload Successfully.", 'Success');

            return redirect(route('appearance.themes.index'));
        } catch (Exception $e) {
            if (is_dir('theme') || is_dir('temp')) {

                $this->delete_directory(base_path('public/theme'));
                $this->delete_directory(base_path('public/temp'));
            }

            Toastr::error($e->getMessage(), trans('common.Failed'));
            return redirect()->back();
        }
    }


    public function show($id)
    {
        try {
            $theme = $this->themeService->showById($id);
            return view('appearance::theme.components.show', compact('theme'));
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }




    public function update(Request $request, $id)
    {
        //
    }


    public function destroy(Request $request)
    {
        if (demoCheck()) {
            return redirect()->back();
        }
        try {
            $this->themeService->delete($request->id);

            $notification = array(
                'messege' => 'Theme Deleted Successfully.',
                'alert-type' => 'success'
            );
            return redirect(route('appearance.themes.index'))->with($notification);
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }
}

Modules/Appearance/Resources/views/theme/index.blade.php
@extends('backend.master')

@push('styles')
    <link rel="stylesheet" href="{{asset('public/backend/css/theme.css')}}"/>
@endpush
@section('mainContent')
    <section class="admin-visitor-area up_st_admin_visitor">
        <div class="container-fluid p-0">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="box_header">
                        <div class="main-title d-flex justify-content-between">
                            <h3 class="mb-0 mr-30">{{ __('setting.Themes') }}</h3>


                            <ul class="d-flex">
                                <li><a class="primary-btn radius_30px mr-10 fix-gr-bg text-white"
                                       href="{{url('/appearance/themes/create')}}"><i
                                            class="ti-plus"></i>{{__('common.Add New')}}</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="row">

                        <div style="position: relative;" class="col-md-4 item_section">
                            <div style="border:2px solid;" class="card">

                                <div style="padding: 0;" class="card-body screenshot">
                                    <div class="single_item_img_div">
                                        <img style="width: 100%" src="{{ asset($activeTheme->image) }}" alt="">
                                    </div>

                                </div>
                                <div class="card-footer">
                                    <div class="row">
                                        <div class="col-5">
                                            <h4>{{$activeTheme->name}}</h4>
                                        </div>
                                        @if($activeTheme->is_active !=1 )
                                            <div class="col-7 footer_div">
                                                <div class="row btn_div">
                                                    <div class="col-md-5 col-sm-12">
                                                        <form action="{{route('appearance.themes.active')}}"
                                                              method="POST">
                                                            @csrf
                                                            <input type="hidden" name="id" value="{{$activeTheme->id}}">
                                                            <button type="submit"
                                                                    class="btn btn-sm btn-outline-secondary Active_btn">{{__('common.active')}}</button>
                                                        </form>

                                                    </div>
                                                    <div style="padding-left: 0;" class="col-md-7 col-sm-12">
                                                        <a class="btn btn-sm btn-outline-secondary Active_btn"
                                                           target="_blank"
                                                           href="{{$activeTheme->live_link}}">{{__('setting.live preview')}}</a>
                                                    </div>
                                                </div>

                                            </div>
                                        @endif
                                    </div>
                                </div>

                                <div class="text-center detail_btn">
                                    <h4>
                                        <a href="{{route('appearance.themes.show',$activeTheme->id)}}">{{__('setting.Theme Details')}}</a>
                                    </h4>
                                </div>

                            </div>


                        </div>

                        @foreach($ThemeList as $key => $item)
                            <div style="position: relative;" class="col-md-4 item_section">
                                <div style="" class="card">

                                    <div style="padding: 0;" class="card-body screenshot">
                                        <div class="single_item_img_div">
                                            <img style="width: 100%" src="{{ asset($item->image) }}" alt="">
                                        </div>

                                    </div>
                                    <div class="card-footer">
                                        <div class="row">
                                            <div class="col-5">
                                                <h4>{{$item->name}}</h4>
                                            </div>
                                            {{-- @if($item->is_active !=1 ) --}}
                                            <div class="col-7 footer_div">
                                                <div class="row btn_div">
                                                    <div class="col-md-5 col-sm-12">
                                                        <form action="{{route('appearance.themes.active')}}"
                                                              method="POST">
                                                            @csrf
                                                            <input type="hidden" name="id" value="{{$item->id}}">
                                                            <button type="submit"
                                                                    class="btn btn-sm btn-outline-secondary Active_btn">
                                                                Active
                                                            </button>
                                                        </form>

                                                    </div>
                                                    <div style="padding-left: 0;" class="col-md-7 col-sm-12">
                                                        <a class="btn btn-sm btn-outline-secondary Active_btn"
                                                           target="_blank" href="{{$item->live_link}}">Live Preview</a>
                                                    </div>
                                                </div>

                                            </div>

                                        </div>
                                    </div>

                                    <div class="text-center detail_btn">
                                        <h4>
                                            <a href="{{route('appearance.themes.show',$item->id)}}">{{__('setting.Theme Details')}}</a>
                                        </h4>
                                    </div>

                                </div>

                            </div>
                        @endforeach


                        <div class="col-md-4">
                            <a href="{{url('/appearance/themes/create')}}">
                                <div id="add_new">
                                    <span id="plus"><i class="fas fa-plus"></i></span>
                                </div>
                            </a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection